# Proxy config for sync-ui

LoadModule session_crypto_module modules/mod_session_crypto.so

RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile /etc/pki/tls/certs/ecs-sync.crt
    SSLCertificateKeyFile /etc/pki/tls/private/ecs-sync.key

    <Location />
        SSLRequireSSL
        AuthFormProvider file
        AuthType form
        AuthName "ECS Sync"
        AuthUserFile /etc/httpd/.htpasswd
        Session On
        SessionCookieName session_id path=/;httponly;secure;
        SessionCryptoPassphrase "exec:/usr/bin/openssl rand -hex 32"
        AuthFormLoginRequiredLocation /login/index.html
        AuthFormLoginSuccessLocation /
        Require valid-user
    </Location>

    <Location /login>
        SSLRequireSSL
        Require all granted
    </Location>

    <Location /custom-errors>
        SSLRequireSSL
        Require all granted
    </Location>

</VirtualHost>

ServerName localhost

ProxyPass "/login" "!"
ProxyPass "/custom-errors" "!"
ProxyPass /rest/ http://localhost:9200/
ProxyPassReverse /rest/ http://localhost:9200/
ProxyPass / http://localhost:8080/
ProxyPassReverse / http://localhost:8080/

# Security Headers including X-Frame-Options and Content Security Policy
Header always set X-Frame-Options "SAMEORIGIN"
Header always set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self';"

# Headers for additional security
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
Header always set X-XSS-Protection "1; mode=block"
Header always set X-Content-Type-Options "nosniff"
Header always set Referrer-Policy "no-referrer-when-downgrade"
Header always edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure;SameSite=Lax
